packages:
  - packages/*
  - packages/sync-protocol/*
  - packages/sync-protocol/*/*
  - packages/treecrdt-wasm-js
  - packages/treecrdt-wa-sqlite/e2e
  - examples/*

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - better-sqlite3
  - esbuild
